#!/bin/sh
# /etc/initramfs-tools/scripts/init-premount/dmintegrity

PREREQ=""
prereqs() {
	echo "$PREREQ"
}

case $1 in
(prereqs)
	prereqs
	exit 0
	;;
esac

. /scripts/functions

log_begin_msg integritysetup open
lcl_lastspace=true
lcl_dev() {
	$lcl_lastspace || _log_msg ' '
	_log_msg "$@"
	lcl_lastspace=true
}
lcl_warn() {
	$lcl_lastspace && _log_msg '\n'
	log_warning_msg "$@"
	lcl_lastspace=false
}

iopen() {
	device=$1
	source=$2
	shift 2
	if test -b "/dev/mapper/$device"; then
		lcl_dev '(%s) ' "$device"
		return 0
	fi
	test -b "$source" || lcl_warn "dmintegrity[$device] source $source missing"
	lcl_dev '%s' "$device"
	integritysetup "$@" open "$source" "$device"
	_log_msg ' '
}

doraid() {
	device=$1
	shift
	if test -b "$device"; then
		lcl_dev '(%s) ' "${device##*/}"
		return 0
	fi
	for source in "$@"; do
		case $source in
		(/dev/*)
			test -b "$source" || \
			    lcl_warn "mdadm[${device##*/}] source $source missing"
			;;
		esac
	done
	lcl_dev '%s' "${device##*/}"
	mdadm --assemble "$device" "$@"
	_log_msg ' '
}

iopen isda /dev/disk/by-partuuid/11111111-02 --allow-discards
iopen isdb /dev/disk/by-partuuid/22222222-02 --allow-discards
# …
doraid /dev/md0 /dev/mapper/isda /dev/mapper/isdb

log_end_msg
exit 0
