#!/bin/sh
# /etc/initramfs-tools/hooks/lcl-integrity

# ⚠ do not forget to add dm_integrity to /etc/initramfs-tools/modules

PREREQ=""
prereqs() {
	echo "$PREREQ"
}

case $1 in
(prereqs)
	prereqs
	exit 0
	;;
esac

. /usr/share/initramfs-tools/hook-functions

copy_exec /sbin/integritysetup
