#!/bin/mksh
# © mirabilos Ⓕ MirBSD

unset LANGUAGE
export LC_ALL=C.UTF-8

function die {
	print -ru2 -- "E: $@"
	exit 1
}

T=$(mktemp -d /tmp/mksh-status.XXXXXXXXXX) || die cannot create temporary directory

rv=0
(
set -e
set -o pipefail
cd "$T"

lynx -source https://buildd.debian.org/status/package.php?p=mksh | \
    tee s.htm | \
    HTML_TIDY=/dev/null tidy -asxhtml -utf8 --newline LF --output-bom no \
    --drop-empty-elements no --drop-empty-paras no --quote-nbsp no --wrap 0 | \
    xmlstarlet fo -e UTF-8 - | \
    sed --posix 's!<html xmlns="http://www.w3.org/1999/xhtml"!<html!' \
    >s.xml

<s.xml >s.lst xmlstarlet sel -T -B -E UTF-8 -t \
    --var linebreak -n --break \
    -m '//table[@class="data"]' \
     -m './tr' \
      -i 'position() > 2' \
	-o 'A: <' \
	-v 'translate(translate(./td[1], $linebreak, " "), "  ↓", "")' \
	-o '> <' \
	-v 'translate(./td[3]/a/@href, $linebreak, " ")' \
	-o '> <' \
	-v 'translate(./td[3]/a, $linebreak, " ")' \
	-o '> :L' -n \
      -b \
     -b \
    -b

set -A archs
narchs=0
set -A logs
set -A states

while IFS=' ' read -r a arch log state l; do
	[[ $a = A: ]] || die "arch $((narchs+1)) beginning broken: ${a@Q} ($arch)"
	[[ $l = :L ]] || die "arch $((narchs+1)) ending broken: ${l@Q} ($arch)"
	[[ $arch = '<'+([0-9a-z-])'>' ]] || die "arch $((narchs+1)) arch broken: ${arch@Q}"
	arch=${arch#'<'}
	arch=${arch%'>'}
	if [[ $log = '<>' ]]; then
		log=
	elif [[ $log != '<fetch.php?'*'>' ]]; then
		die "arch $((narchs+1)) log broken: ${log@Q} ($arch)"
	else
		log=https://buildd.debian.org/status/${log#'<'}
		log=${log%'>'}
	fi
	[[ $state = '<'*'>' ]] || \
	    die "arch $((narchs+1)) state broken: ${state@Q} ($arch)"
	state=${state#'<'}
	state=${state%'>'}
	case $arch in
	(hurd-i386) arch=hurd ;;
	(hurd*) die "another hurd* found: ${arch@Q}" ;;
	(kfreebsd-i386) arch=k-i386 ;;
	(kfreebsd-amd64) arch=k-amd64 ;;
	(k-*|kfreebsd*) die "another k(freebsd)* found: ${arch@Q}" ;;
	esac
	[[ -n $log ]] && logs[narchs]=$log
	states[narchs]=$state
	archs[narchs++]=$arch
	# debugging
	:||if [[ $arch = alpha ]]; then
		archs[narchs++]=avr32
	fi
done <s.lst

print -ru2 -- "I: found $narchs architectures, ${#logs[*]} with logs"
print -ru2 -- N: "${archs[@]}"

i=-1
while (( ++i < narchs )); do
	[[ -n ${logs[i]} ]] || continue
	wget --quiet --show-progress -O arch."${archs[i]}" "${logs[i]}&raw=1"
done

cat >columnus <<-'EOF'
	arch)prog)system)klibc)musl)dietlibc)glibc
EOF

i=-1
while (( ++i < narchs )); do
	if [[ -z ${logs[i]} ]]; then
		cat >>columnus <<-EOF
			${archs[i]})-)⁉ missing)⁉ missing)⁉ missing)⁉ missing)⁉ absent
		EOF
		continue
	fi
	fn=arch.${archs[i]}

	llc=$(sed --posix -n \
	    -e '/^D:loglibc:start(\([^)]*\)) \(.*\) initialising$/s//vs=v\1 \2/p' \
	    -e '/^D:loglibc:final(\([^)]*\)) \(.*\) finishing$/s//vt=v\1 \2/p' \
	    "$fn" | sed --posix 's/ \([a-z][a-z0-9_]*=\)/\nvv\1/g' | sed --posix \
	    -e 's!_(\([0-9]*\)_unexpected)f!f/\1u!' \
	    -e 's/RTCHK/rtchk/g' -e 's/MTEST/mtest/g' \
	    -e 's/testsuite-failed/fail/g' \
	    -e 's/passed-but-notty/ntty/g' \
	    -e 's/succeeded-tested/succ/g' \
	    -e 's/_([^) ]*)//' \
	    -e "s/'/'\\\\''/g" -e 's/=\(.*\)$/='\''\1'\''/')
	case $nl$llc in (*"${nl}vs="*"${nl}vs="*)
		echo >&2 "W: multiple loglibc:start lines; log is fishy: $fn" ;;
	esac
	case $nl$llc in (*"${nl}vt="*"${nl}vt="*)
		echo >&2 "W: multiple loglibc:final lines; log is fishy: $fn" ;;
	esac
	vs= vt= vvarch= vvbred= vvsystem=
	vvmksh_klibc= vvmksh_musl= vvmksh_dietlibc= vvmksh_glibc=
	vvlksh_klibc= vvlksh_musl= vvlksh_dietlibc= vvlksh_glibc=
	eval "$llc"
	if test -z "$vs"; then
		vs=$vt vvarch= vvbred=
	fi
	if test -z "$vt"; then
		vt=$vs vvsystem=
		vvmksh_klibc= vvmksh_musl= vvmksh_dietlibc= vvmksh_glibc=
		vvlksh_klibc= vvlksh_musl= vvlksh_dietlibc= vvlksh_glibc=
	fi
	case x$vvbred in
	x|x0)
		bred=↑
		;;
	x1)
		bred=⇑
		;;
	*)
		echo >&2 "W: invalid bred ($vvbred); log is fishy: $fn"
		bred=⇓
		;;
	esac
	test x"$vs" = x"$vt" || echo >&2 "W: version difference" \
	    "($vs) vs. ($vt); log is fishy: $fn"
	vsn=${vs#v}

	case $vsn:${states[i]} {
	(:Build-Attempted|:Failed)
		vsn=$(sed --posix -n '/^Version: /{s///p;q;}' <"$fn")
		vsn=⸘${vsn:-'¿?'}
		vvmksh_glibc=⸘${states[i]}${vvmksh_glibc:+ $vvmksh_glibc}
		;;
	(*)
		vsn='('${vsn:-¿?}
	}
	cat >>columnus <<-EOF
		${archs[i]})mksh)${vvsystem:-⁉ unset})${vvmksh_klibc:-⁉ unset})${vvmksh_musl:-⁉ unset})${vvmksh_dietlibc:-⁉ unset})${vvmksh_glibc:-⁉ unset}
		${vvarch:- })lksh) $bred version$vsn)${vvlksh_klibc:-⁉ unset})${vvlksh_musl:-⁉ unset})${vvlksh_dietlibc:-⁉ unset})${vvlksh_glibc:-⁉ unset}
	EOF
done

column -ts')' <columnus >tabularis
ed -s tabularis <<-\EOF
	,g/✓[^ ]*/s//[0;1;30;40m&/g
	,g/？[^ ]*/s//[0;33;40m&/g
	,g/⁉[^ ]*/s//[0;1;33;40m&/g
	,g/⁇[^ ]*/s//[0;35,40m&/g
	,g/✘[^ ]*/s//[0;1;31;40m&/g
	,g/✗[^ ]*/s//[0;31;40m&/g
	,g/☒[^ ]*/s//[0;1;35;40m&/g
	,g/✔[^ ]*/s//[0;1;32;40m&/g
	,g/ ↑\([^(]*\)(\([^ ]*\) /s//[0;1;30;40m ↑\1 [0;1m\2 /
	,g/ ↑\(.*\)⸘\([^ ]*\) /s//[0;36;40m ↑\1 [1m\2 /
	,g/ ⇑\([^(]*\)(\([^ ]*\) /s//[0;1;30;40m ↑\1 [0;31;1m\2 /
	,g/ ⇑\(.*\)⸘\([^ ]*\) /s//[0;36;40m ↑\1 [31;1m\2 /
	,g/ ⇓\([^(]*\)(\([^ ]*\) /s//[0;1;30;40m ↑\1 [0;5;1m\2 /
	,g/ ⇓\(.*\)⸘\([^ ]*\) /s//[0;36;40m ↑\1 [5;1m\2 /
	,g/⸘/s//[0;1;36;40m/g
	1s/^/[0m/
	1s/  */&| /g
	1s/$/   /
	2,$g/^[^ ]/s//[0;1;34;40m&/
	2,$g/  */s//[0m&| /g
	,g/ |/s//|/g
	1t$
	2,$g/^[^m]*m[^ ]/.-1s/.0/&;4/g
	,g/^/s//[0;4m/
	,g/$/s//[0m/
	w
	q
EOF

echo
cat tabularis
print -nr -- "[0;1;30;40m⇐ $PWD ⇒ press Return to continue…[0m"
read

) || rv=1
cd /
rm -rf "$T"
exit $rv
